logo: "/assets/images/logo-lcc.png"
favicon: "/assets/images/favicon.ico"

title: Documentation for LCC Hub
description: Knowledge transfer for upcoming students doing their social service
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/CC-unison/documentation-lcchub

aux_links_new_tab: true
