title: La Documentación del LCCHub
description: Porque apretamos pero no ahorcamos
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/CC-unison/documentation-lcchub

aux_links_new_tab: true
